config/routes.rb
Sop::Application.routes.draw do

  resources :firms do
    resources :documents
  end

  match 'documents/search', :controller => 'documents', :action => 'search'

  resources :documents do
    resources :firms
  end

  resources :notes do
    resources :firms
  end

  resources :firms do
    resources :notes
  end

root :to => "home#index"

end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :filename, :documenttype, :firm, :fund, :group, :investmentcat, :month, :url, :year, :firm_ids
  has_and_belongs_to_many :firms

  include Tire::Model::Search
  include Tire::Model::Callbacks

  def self.search(params)
    tire.search(load: true) do
      query { string params[:query], default_operator: "AND" } if params[:query].present?

    end
  end
end

app/models/firm.rb
class Firm < ActiveRecord::Base
  attr_accessible :emergency_phone, :fax, :firm_name, :firm_type, :phone, :short_name, :status, :website, :document_ids
  has_and_belongs_to_many :documents
  has_and_belongs_to_many :notes
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :city, :content, :format, :meeting_time, :state, :street, :summary, :title, :type, :zip, :firm_ids
  has_and_belongs_to_many :firms
  # has_and_belongs_to_many :
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  def widget
    @documents = Document.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
    end
  end

  def index
    @documents = Document.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  def search
    @search_results = []

    unless params[:query].nil? || params[:query].strip.empty?
      @search_results = Document.search(params)
    end
    @search_results
    # AJ - including respond_to block breaks search
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(params[:document])

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/firms_controller.rb
class FirmsController < ApplicationController

  def widget
    @firms = Firm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @firms }
    end
  end

  # GET /firms
  # GET /firms.json
  def index
    @firms = Firm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @firms }
    end
  end

  # GET /firms/1
  # GET /firms/1.json
  def show
    @firm = Firm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @firm }
    end
  end

  # GET /firms/new
  # GET /firms/new.json
  def new
    @firm = Firm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @firm }
    end
  end

  # GET /firms/1/edit
  def edit
    @firm = Firm.find(params[:id])
  end

  # POST /firms
  # POST /firms.json
  def create
    @firm = Firm.new(params[:firm])

    respond_to do |format|
      if @firm.save
        format.html { redirect_to @firm, notice: 'Firm was successfully created.' }
        format.json { render json: @firm, status: :created, location: @firm }
      else
        format.html { render action: "new" }
        format.json { render json: @firm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /firms/1
  # PUT /firms/1.json
  def update
    @firm = Firm.find(params[:id])

    respond_to do |format|
      if @firm.update_attributes(params[:firm])
        format.html { redirect_to @firm, notice: 'Firm was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @firm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firms/1
  # DELETE /firms/1.json
  def destroy
    @firm = Firm.find(params[:id])
    @firm.destroy

    respond_to do |format|
      format.html { redirect_to firms_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # GET /notes
  # GET /notes.json

    def widget
    @notes = Note.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notes }
    end
  end

  def index
    @notes = Note.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render json: @note, status: :created, location: @note }
      else
        format.html { render action: "new" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/firms_helper.rb
module FirmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/documents/_documents.html.haml
%table
  - @search_results.each do |document|
    %tr
      %td= link_to (document.filename), document
      %td= link_to 'Open', document
      %td= link_to 'Edit', edit_document_path(document)
      / %td= link_to 'Delete', document, :confirm => 'Are you sure?', :method => :delete

app/views/documents/_form.html.haml
- @firms = Firm.all

= form_for @document do |f|
  -if @document.errors.any?
    #error_explanation
      %h2= "#{pluralize(@document.errors.count, "error")} prohibited this document from being saved:"
      %ul
        - @document.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :filename
    = f.text_field :filename
  .field
    = f.label :documenttype
    = f.text_field :documenttype
  .field
    = f.label :firm_id
    = f.collection_select(:firm_ids, Firm.all, :id, :firm_name)
  .field
    = f.label :fund
    = f.text_field :fund
  .field
    = f.label :month
    = f.text_field :month
  .field
    = f.label :year
    = f.number_field :year
  .field
    = f.label :group
    = f.select :group, ['lcc', 'mcc', 'privates']
  .field
    = f.label :investmentcat
    = f.text_field :investmentcat
  .field
    = f.label :url
    = f.text_field :url

  .actions
    = f.submit 'Save'

app/views/documents/_widget.html.haml
.widget
  - @documents.each do |document|
    .row
      .firm-name
        %p= link_to document.filename, document

app/views/documents/all.html.haml
%table
  - @documents.each do |document|
    %tr
      %td= document.filename
      %td= document.documenttype
      %td= document.firm_id
      %td= document.fund
      %td= document.month
      %td= document.year
      %td= document.group
      %td= document.investmentcat
      %td= document.url

      %td= link_to 'Show', document
      %td= link_to 'Edit', edit_document_path(document)
      %td= link_to 'Destroy', document, :confirm => 'Are you sure?', :method => :delete
%br

= link_to 'New Document', new_document_path

app/views/documents/edit.html.haml
%h1 Editing document

= render 'form'

= link_to 'Show', @document
\|
/ = link_to 'Back', documents_path

app/views/documents/index.html.haml
%table
  - @documents.each do |document|
    %tr
      %td= document.filename
      %td= document.documenttype
      %td= document.firm_ids
      %td= document.fund
      %td= document.month
      %td= document.year
      %td= document.group
      %td= document.investmentcat
      %td= document.url

      %td= link_to 'Show', document
      %td= link_to 'Edit', edit_document_path(document)
      %td= link_to 'Destroy', document, :confirm => 'Are you sure?', :method => :delete
%br

= link_to 'New Document', new_document_path

app/views/documents/index.js.erb
//= require jquery

$('#documents').html("<%= escape_javascript(render :partial => "documents") %>");

app/views/documents/new.html.haml
%h1 New document

= render 'form'

= link_to 'Back', documents_path

app/views/documents/search.html.haml
.search-form
  .green
    = form_tag({:controller => "documents", :action => "search"}, method: :get, id: "documents_search") do
      = text_field_tag :query, params[:query], :placeholder => 'Enter Search...'

#documents
  = render partial: 'documents/documents'

/ %br

/ = link_to 'New Document', new_document_path

app/views/documents/search.js.erb
//= require jquery

$('#documents').html("<%= escape_javascript(render :partial => "documents") %>");

app/views/documents/show.html.haml
%p#notice= notice

%p
  %b Filename:
  = @document.filename
%p
  %b Type:
  = @document.documenttype
%p
  %b Firm:
  = @document.firm_ids
%p
  %b Fund:
  = @document.fund
%p
  %b Month:
  = @document.month
%p
  %b Year:
  = @document.year
%p
  %b Group:
  = @document.group
%p
  %b Investmentcat:
  = @document.investmentcat
%p
  %b Url:
  = @document.url

= link_to 'Edit', edit_document_path(@document)
\|
= link_to 'Back', documents_path

app/views/firms/_detail.html.haml
.detail
%ul
  %li
    %b Short Name:
    = @firm.short_name
  %li
    %b Firm Type:
    = @firm.firm_type
  %li
    %b Phone:
    = number_to_phone(@firm.phone)
  %li
    %b Fax:
    = number_to_phone(@firm.fax)
  %li
    %b Emergency:
    = number_to_phone(@firm.emergency_phone)
  %li
    %b Website:
    = @firm.website
  %li
    %b Status:
    = @firm.status

app/views/firms/_form.html.haml
= form_for @firm do |f|
  -if @firm.errors.any?
    #error_explanation
      %h2= "#{pluralize(@firm.errors.count, "error")} prohibited this firm from being saved:"
      %ul
        - @firm.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :firm_name
    = f.text_field :firm_name
  .field
    = f.label :short_name
    = f.text_field :short_name
  .field
    = f.label :firm_type
    = f.text_field :firm_type
  .field
    = f.label :phone
    = f.number_field :phone
  .field
    = f.label :fax
    = f.number_field :fax
  .field
    = f.label :emergency_phone
    = f.number_field :emergency_phone
  .field
    = f.label :website
    = f.text_field :website
  .field
    = f.label :status
    = f.text_field :status
  .field
    = f.label :document_ids
    = f.collection_select(:document_ids, Document.all, :id, :filename)
  .actions
    = f.submit 'Save'

app/views/firms/_widget.html.haml
.widget
  - @firms.each do |firm|
    .row
      %ul
        %li= link_to firm.firm_name, firm
        %li New York, NY
        %li p: #{number_to_phone(firm.phone)}

app/views/firms/edit.html.haml
%h1 Editing firm

= render 'form'

= link_to 'Show', @firm
\|
/ = link_to 'Back', firms_path

app/views/firms/index.html.haml
.content
  .title
    %h1 Firms
  .main
    .documents-container.mainwidth
      .tabs
        %p Firms
        %ul
          %li Recent
          %li All
        .buttons.view-all
          %b= link_to 'view all', firms_path
      .container-box.mainwidth
        = render partial: 'firms/widget'

    / .documents-container.mainwidth
    /   .tabs
    /     %p Recently Visited
    /     %ul
    /       %li Recent
    /       %li All
    /     .buttons.view-all
    /       %b= link_to 'view all', notes_path
    /   .container-box.mainwidth

  .sidebar
    .documents-container.sidebarwidth
      .tabs
        %p Investments
        %ul
          %li Yours
          %li Group
      .container-box.sidebarwidth
        = render partial: 'firms/widget'

    .documents-container.sidebarwidth
      .tabs
        %p Emails
        %ul
          %li Yours
          %li Group
      .container-box.sidebarwidth

/ %table
/   %tr
/     %th Firm name
/     %th Short name
/     %th Firm type
/     %th Phone
/     %th Fax
/     %th Emergency phone
/     %th Website
/     %th Status
/     %th Document
/     %th
/     %th
/     %th

/   - @firms.each do |firm|
/     %tr
/       %td= firm.firm_name
/       %td= firm.short_name
/       %td= firm.firm_type
/       %td= firm.phone
/       %td= firm.fax
/       %td= firm.emergency_phone
/       %td= firm.website
/       %td= firm.status
/       %td= firm.document_ids
/       %td= link_to 'Show', firm
/       %td= link_to 'Edit', edit_firm_path(firm)
/       %td= link_to 'Destroy', firm, :confirm => 'Are you sure?', :method => :delete

/ %br

/ = link_to 'New Firm', new_firm_path

app/views/firms/new.html.haml
%h1 New firm

= render 'form'

= link_to 'Back', firms_path

app/views/firms/show.html.haml
- @documents = Firm.find(params[:id]).documents
- @notes = Firm.find(params[:id]).notes

.content
  .title
    %h1= @firm.firm_name
  .main
    .documents-container.mainwidth
      .tabs
        %p Documents
        %ul
          %li Recent
          %li All
      .container-box.mainwidth
        .widget
          = render partial: 'documents/widget'

    .documents-container.mainwidth
      .tabs
        %p Notes
        %ul
          %li Recent
          %li All
      .buttons.new
        %b= link_to 'new note', new_note_path
      .container-box.mainwidth
        .widget
          = render partial: 'notes/widget'
  .sidebar
    .documents-container.sidebarwidth
      .tabs
        %p Favorites
        %ul
          %li Yours
          %li Group
      .container-box.sidebarwidth
    .documents-container.sidebarwidth
      .tabs
        %p Account Detail
      .buttons.edit
        %b= link_to 'edit', edit_firm_path(@firm)
      .container-box.sidebarwidth
        = render partial: 'firms/detail'

    / %p#notice= notice


    / %p
    /   %b Document:
    /   = @firm.document_id

    / = link_to 'Edit', edit_firm_path(@firm)
    / \|
    / = link_to 'Back', firms_path

app/views/home/index.html.haml
- @documents = Document.all
- @firms = Firm.all
- @notes = Note.all

.content
  .title
    %h1 UTRaCs Home
  .main
    .documents-container.mainwidth
      .tabs
        %p Documents
        %ul
          %li Recent
          %li All
        .buttons.view-all
          %b= link_to 'view all', documents_path
      .container-box.mainwidth
        = render partial: 'documents/widget'

    .documents-container.mainwidth
      .tabs
        %p Notes
        %ul
          %li Recent
          %li All
        .buttons.view-all
          %b= link_to 'view all', notes_path
      .container-box.mainwidth
        = render partial: 'notes/widget'
  .sidebar
    .documents-container.sidebarwidth
      .tabs
        %p Investments
        %ul
          %li Yours
          %li Group
      .container-box.sidebarwidth
        = render partial: 'firms/widget'

    .documents-container.sidebarwidth
      .tabs
        %p Emails
        %ul
          %li Yours
          %li Group
      .container-box.sidebarwidth

//launch elastic search with: elasticsearch -f -D es.config=/usr/local/Cellar/elasticsearch/0.18.7/config/elasticsearch.ym

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title UTIMCO
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render partial: 'shared/toolbar'
    = render partial: 'shared/subtoolbar'
    .body
      = yield

app/views/notes/_form.html.haml
= form_for @note do |f|
  -if @note.errors.any?
    #error_explanation
      %h2= "#{pluralize(@note.errors.count, "error")} prohibited this note from being saved:"
      %ul
        - @note.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :summary
    = f.text_field :summary
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :format
    = f.text_field :format
  .field
    = f.label :meeting_type
    = f.text_field :meeting_type
  .field
    = f.label :meeting_time
    = f.datetime_select :meeting_time
  .field
    = f.label :street
    = f.text_field :street
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :state
    = f.text_field :state
  .field
    = f.label :zip
    = f.number_field :zip
  .field
    = f.label :firm_id
    = f.collection_select(:firm_ids, Firm.all, :id, :firm_name)
  .actions
    = f.submit 'Save'

app/views/notes/_widget.html.haml
.widget.note
  - @notes.each do |note|
    .row
      .note-name
        %p= link_to note.title, note
      .info
        %p= note.summary
      .commentary.fourteen
        %b= note.content

app/views/notes/edit.html.haml
%h1 Editing note

= render 'form'

= link_to 'Show', @note
\|
/ = link_to 'Back', notes_path

app/views/notes/index.html.haml
%h1 Listing notes

%table
  %tr
    %th Title
    %th Summary
    %th Content
    %th Format
    %th Meeting Type
    %th Meeting time
    %th Street
    %th City
    %th State
    %th Zip
    %th
    %th
    %th

  - @notes.each do |note|
    %tr
      %td= note.title
      %td= note.summary
      %td= note.content
      %td= note.format
      %td= note.meeting_type
      %td= note.meeting_time
      %td= note.street
      %td= note.city
      %td= note.state
      %td= note.zip
      %td= note.firm_ids
      %td= link_to 'Show', note
      %td= link_to 'Edit', edit_note_path(note)
      %td= link_to 'Destroy', note, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Note', new_note_path

app/views/notes/new.html.haml
%h1 New note

= render 'form'

= link_to 'Back', notes_path

app/views/notes/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @note.title
%p
  %b Summary:
  = @note.summary
%p
  %b Content:
  = @note.content
%p
  %b Format:
  = @note.format
%p
  %b Meeting Type:
  = @note.meeting_type
%p
  %b Meeting time:
  = @note.meeting_time
%p
  %b Street:
  = @note.street
%p
  %b City:
  = @note.city
%p
  %b State:
  = @note.state
%p
  %b Zip:
  = @note.zip
%p
  %b Firm:
  = @note.firm_ids

= link_to 'Edit', edit_note_path(@note)
\|
= link_to 'Back', notes_path

app/views/shared/_subtoolbar.html.haml
.subtoolbar
  #tabs
    #utracs-tab
      %ul#nav
        %li
          %p= link_to 'Home', :root
        %li
          %p= link_to "Firms", firms_path
          %ul
            %li
              %a{:href => "#"} Prospects
            %li
              %a{:href => "#"} Existing
        %li
          %p Contacts
          %ul
            %li
              %a{:href => "#"} Existing
            %li
              %a{:href => "#"} Prospects
            %li
              %a{:href => "#"} Service Providers
            %li
              %a{:href => "#"} Other
        %li
          %p= link_to 'Notes', notes_path
          %ul
            %li
              %a{:href => "#"} LCC
            %li
              %a{:href => "#"} MCC
            %li
              %a{:href => "#"} Privates
            %li
              %a{:href => "#"} Real Estate
            %li
              %a{:href => "#"} Natural Resources
            %li
              %a{:href => "#"} All
        %li
          %p= link_to 'Documents', documents_path

    #groups-tab
      %ul
        %li Privates
        %li MCC
        %li LCC
        %li Natural Resources
        %li Real Estate
        %li Risk
        %li Accounting
    #apps-tab
      %ul
        %li Pricing
        %li MARS
        %li Bondedge
        %li Travel Calendar
        %li Daily Performance
        %li Mellon Downloads
        %li More...
    #staff-tab
      %ul
        %li Policies
        %li Retirement
        %li Insurance
        %li Comp Program
        %li Compliance Hotline
        %li Holidays
        %li Employee Directory
    #favorites-tab
      %ul
        %li LCC
        %li Notes
        %li Maverick
        %li Perry
        %li MARS
        %li Mellon Downloads
        %li Contacts
    #settings-tab
      / %ul
      /   %li Privates
      /   %li MCC
      /   %li LCC
      /   %li Natural Resources
      /   %li Real Estate
      /   %li Risk
      /   %li Accounting

app/views/shared/_toolbar.html.haml
- @search_results = []

.toolbar
  .toolbar-box
    .logo
      %h1= link_to 'UTIMCO', :root
    .navigation
      #tabs
        %ul#main-nav
          %li
            %a{:href => "#utracs-tab", :id => "#utracs"}UTRaCs
          %li
            %a{:href => "#groups-tab", :id => "groups"}Groups
          %li
            %a{:href => "#apps-tab", :id => "apps"}Apps
          %li
            %a{:href => "#staff-tab", :id => "staff"}Staff
          %li
            %a{:href => "#favorites-tab", :id => "favorites"}Favorites
          %li
            %a{:href => "#settings-tab", :id => "settings"}Settings

    .search
      .search-box
        = render template: 'documents/search'
      .search-help